### ISSUE TITLE
Add job_id to worker

### ISSUE THREAD

**Issue by manglav** [SaladTechnologies/kelpie#9]
{ ...work.environment, INPUT_DIR, OUTPUT_DIR, CHECKPOINT_DIR }
 
 { ...work.environment, INPUT_DIR, OUTPUT_DIR, CHECKPOINT_DIR, SALAD_JOB_ID: work.id }

Can we add the salad job_id to the worker has access to it for logging purposes?

**Comment by shawnrushefsky** [comment]
This will be included in the next release `0.5.0`. There's a draft PR in #8 if you want to track the status.
